# Generated by Django 5.1.3 on 2024-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("año_fundacion", models.DateTimeField()),
                ("apodo", models.CharField(max_length=30)),
                ("estadio", models.CharField(max_length=50)),
                ("escudo", models.FileField(upload_to="equipos/")),
            ],
        ),
    ]
