# Generated by Django 5.1.3 on 2024-11-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="año_fundacion",
            field=models.CharField(max_length=50),
        ),
    ]
