# Generated by Django 5.1.3 on 2024-11-21 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crud", "0002_alter_equipo_año_fundacion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipo",
            old_name="año_fundacion",
            new_name="fundacion",
        ),
    ]
